# Configuración de conexión con MySQL

spring.datasource.url=jdbc:mysql://localhost:3306/conexionreal

spring.datasource.username=root

spring.datasource.password=anclalia1524


# Configuración de JPA

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true